"""Initial tables

Revision ID: 3f1710aae359
Revises: 
Create Date: 2025-06-16 20:17:10.769204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f1710aae359'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    op.create_table('pets',
    sa.Column('id', sa.Integer(), primary_key=True),  # ✅ FIXED
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('subspecies', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('profile_image_id', sa.Integer(), nullable=True),
    sa.Column('profile_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id']),
    # sa.ForeignKeyConstraint(['profile_image_id'], ['uploaded_files.id']),
    )

    op.create_table(
        'uploaded_files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pet_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('stored_filename', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('subcategory', sa.String(length=50), nullable=True),
        sa.Column('label', sa.String(length=100), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('file_hash', sa.String(length=64), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')  # ← ✅ closing correctly here
    )
    op.create_foreign_key(
        "fk_uploaded_files_pet_id_pets",
        "uploaded_files", "pets",
        ["pet_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_uploaded_files_user_id_users",
        "uploaded_files", "users",
        ["user_id"], ["id"]
    )

    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'FAMILY_MEMBER', 'CO_PARENT', 'PARTNER', 'ROOMMATE', 'NEIGHBOR', 'SITTER', name='roletype'), nullable=False),
    sa.Column('access_level', sa.Enum('ADMIN', 'FULL_ACCESS', 'VIEW_ALL', 'VIEW_LIMITED', name='accesslevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('weight_updated', sa.String(length=20), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('ADMIN', 'FULL_ACCESS', 'VIEW_ALL', 'VIEW_LIMITED', name='accesslevel'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_things', sa.Text(), nullable=False),
    sa.Column('dislikes', sa.Text(), nullable=False),
    sa.Column('social_style', sa.Text(), nullable=False),
    sa.Column('communication', sa.Text(), nullable=False),
    sa.Column('preferred_treats', sa.Text(), nullable=False),
    sa.Column('diet', sa.Text(), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=False),
    sa.Column('medical_alerts', sa.Text(), nullable=False),
    sa.Column('behavior_notes', sa.Text(), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'FAMILY_MEMBER', 'CO_PARENT', 'PARTNER', 'ROOMMATE', 'NEIGHBOR', 'SITTER', name='roletype'), nullable=False),
    sa.Column('access_level', sa.Enum('ADMIN', 'FULL_ACCESS', 'VIEW_ALL', 'VIEW_LIMITED', name='accesslevel'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('sitter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('invitation_status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='invitationstatus'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('access_level', sa.Enum('ADMIN', 'FULL_ACCESS', 'VIEW_ALL', 'VIEW_LIMITED', name='accesslevel'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['sitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('care_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pronouns', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=300), nullable=True),
    sa.Column('profile_description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('languages_spoken', sa.String(length=100), nullable=True),
    sa.Column('experience_with', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('certification_files', sa.String(length=300), nullable=True),
    sa.Column('public_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('medical_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_profile_id'], ['medical_profiles.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('medical_profile_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_profile_id'], ['medical_profiles.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('medical_profile_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('previous_vaccination_date', sa.Date(), nullable=True),
    sa.Column('next_vaccination_date', sa.String(length=50), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_profile_id'], ['medical_profiles.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vet_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('medical_profile_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.Column('clinic_info', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['medical_profile_id'], ['medical_profiles.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('medical_profile_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('vet_visit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medical_profile_id'], ['medical_profiles.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['vet_visit_id'], ['vet_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vet_visit_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vet_visit_id', sa.Integer(), nullable=False),
    sa.Column('medical_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medical_document_id'], ['medical_documents.id'], ),
    sa.ForeignKeyConstraint(['vet_visit_id'], ['vet_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vet_visit_documents')
    op.drop_table('medical_documents')
    op.drop_table('vet_visits')
    op.drop_table('vaccination_records')
    op.drop_table('test_results')
    op.drop_table('medications')
    op.drop_table('user_profiles')
    op.drop_table('tasks')
    op.drop_table('sitters')
    op.drop_table('roles')
    op.drop_table('pet_data')
    op.drop_table('permissions')
    op.drop_table('medical_profiles')
    op.drop_table('invitations')
    op.drop_table('users')
    op.drop_table('uploaded_files')
    op.drop_table('pets')
    # ### end Alembic commands ###
