"""Fix casing: additional_info

Revision ID: 1b43e7928e1c
Revises: e2eec1e34d33
Create Date: 2025-04-15 16:17:53.191442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b43e7928e1c'
down_revision = 'e2eec1e34d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.drop_column('additional_Info')

    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.drop_column('additional_Info')

    with op.batch_alter_table('vaccination_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.drop_column('additional_Info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_Info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_info')

    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_Info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_info')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_Info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###
