"""Make phone optional

Revision ID: 542bdba117a7
Revises: 2dde900db3ac
Create Date: 2025-04-09 15:10:23.097491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542bdba117a7'
down_revision = '2dde900db3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
